Q.4 Limit the number of items printed in python NumPy array a to a maximum of 6
elements.
Input:
array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
Desired Output:
array([ 0, 1, 2, ..., 12, 13, 14])

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])

In [ ]:
np.set_printoptions(threshold=6)

In [ ]:
a

array([ 1,  2,  3, ..., 12, 13, 14])