Q.3 Get all items between 5 and 10 from a.
Input:
a = np.array([2, 6, 1, 9, 10, 3, 27])
Desired Output:
(array([6, 9, 10]),)


In [ ]:
import numpy as np

In [ ]:
a = np.array([2,6,1,9,10,3,27])

In [ ]:
result = a[(a>=5) & (a<=10)]

In [ ]:
result

array([ 6,  9, 10])

In [ ]:
print(result)

[ 6  9 10]
